# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'travel.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class checklist(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 891)
        MainWindow.setStyleSheet("backgroud: opacity 0;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-image: url(./images/back.jpg);\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 80, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Luckiest Guy")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAcceptDrops(False)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: white;\n"
"background: opacity 0;\n"
"\n"
"")
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 470, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Merienda")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("font-family: \'Merienda\';\n"
"color: #fff;\n"
"font-weight: bold;\n"
"font-size: 22px;\n"
"background: opacity 0;")
        self.label_2.setObjectName("label_2")
        self.incountry_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_cb.setGeometry(QtCore.QRect(240, 170, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_cb.setFont(font)
        self.incountry_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_cb.setObjectName("incountry_cb")
        self.incountry_warm_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_warm_cb.setGeometry(QtCore.QRect(40, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_warm_cb.setFont(font)
        self.incountry_warm_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_warm_cb.setObjectName("incountry_warm_cb")
        self.incountry_cold_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_cold_cb.setGeometry(QtCore.QRect(470, 260, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_cold_cb.setFont(font)
        self.incountry_cold_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_cold_cb.setObjectName("incountry_cold_cb")
        self.incountry_beach_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_beach_cb.setGeometry(QtCore.QRect(40, 330, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_beach_cb.setFont(font)
        self.incountry_beach_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_beach_cb.setObjectName("incountry_beach_cb")
        self.incountry_warm_buisnesstrip_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_warm_buisnesstrip_cb.setGeometry(QtCore.QRect(40, 400, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_warm_buisnesstrip_cb.setFont(font)
        self.incountry_warm_buisnesstrip_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_warm_buisnesstrip_cb.setObjectName("incountry_warm_buisnesstrip_cb")
        self.incountry_mountains_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_mountains_cb.setGeometry(QtCore.QRect(470, 330, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_mountains_cb.setFont(font)
        self.incountry_mountains_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_mountains_cb.setObjectName("incountry_mountains_cb")
        self.incountry_cold_buisnesstrip_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.incountry_cold_buisnesstrip_cb.setGeometry(QtCore.QRect(390, 400, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.incountry_cold_buisnesstrip_cb.setFont(font)
        self.incountry_cold_buisnesstrip_cb.setStyleSheet("background: opacity 0;\n"
"color: #ADFF2F;")
        self.incountry_cold_buisnesstrip_cb.setObjectName("incountry_cold_buisnesstrip_cb")
        self.outcountry_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_cb.setGeometry(QtCore.QRect(230, 520, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_cb.setFont(font)
        self.outcountry_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;")
        self.outcountry_cb.setObjectName("outcountry_cb")
        self.outcountry_warm_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_warm_cb.setGeometry(QtCore.QRect(40, 570, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_warm_cb.setFont(font)
        self.outcountry_warm_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcountry_warm_cb.setObjectName("outcountry_warm_cb")
        self.outcountry_cold_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_cold_cb.setGeometry(QtCore.QRect(480, 570, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_cold_cb.setFont(font)
        self.outcountry_cold_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcountry_cold_cb.setObjectName("outcountry_cold_cb")
        self.outcountry_warm_hike_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_warm_hike_cb.setGeometry(QtCore.QRect(40, 740, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_warm_hike_cb.setFont(font)
        self.outcountry_warm_hike_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcountry_warm_hike_cb.setObjectName("outcountry_warm_hike_cb")
        self.outcountry_warm_excursion_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_warm_excursion_cb.setGeometry(QtCore.QRect(40, 660, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_warm_excursion_cb.setFont(font)
        self.outcountry_warm_excursion_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcountry_warm_excursion_cb.setObjectName("outcountry_warm_excursion_cb")
        self.outcounty_cold_excursion_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcounty_cold_excursion_cb.setGeometry(QtCore.QRect(450, 670, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcounty_cold_excursion_cb.setFont(font)
        self.outcounty_cold_excursion_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcounty_cold_excursion_cb.setObjectName("outcounty_cold_excursion_cb")
        self.outcountry_cold_hike_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.outcountry_cold_hike_cb.setGeometry(QtCore.QRect(360, 740, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Sports World")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.outcountry_cold_hike_cb.setFont(font)
        self.outcountry_cold_hike_cb.setStyleSheet("background: opacity 0;\n"
"color: #FF69B4;\n"
"")
        self.outcountry_cold_hike_cb.setObjectName("outcountry_cold_hike_cb")
        self.button_travel = QtWidgets.QPushButton(self.centralwidget)
        self.button_travel.setGeometry(QtCore.QRect(170, 820, 321, 41))
        self.button_travel.setStyleSheet("QPushButton{\n"
"background-color: #425865;\n"
"border: 2px solid #425865;\n"
"border-radius: 30px;\n"
"color: white;\n"
"font-family: \'Luckiest Guy\', cursive;\n"
"font-size: 15px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #fa4244;\n"
"}")
        self.button_travel.setObjectName("button_travel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"</style></head><body style=\" font-family:\'Luckiest Guy\',\'cursive\'; font-size:45px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:27pt;\">Tick your variant</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "GET READY FOR A TRIP WITHOUT ANY PROBLEMS!"))
        self.incountry_cb.setText(_translate("MainWindow", "ПО СТРАНЕ"))
        self.incountry_warm_cb.setText(_translate("MainWindow", "ТЕПЛО"))
        self.incountry_cold_cb.setText(_translate("MainWindow", "ХОЛОДНО"))
        self.incountry_beach_cb.setText(_translate("MainWindow", "ПЛЯЖ"))
        self.incountry_warm_buisnesstrip_cb.setText(_translate("MainWindow", "КОМАНДИРОВКА"))
        self.incountry_mountains_cb.setText(_translate("MainWindow", "ГОРЫ"))
        self.incountry_cold_buisnesstrip_cb.setText(_translate("MainWindow", "КОМАНДИРОВКА"))
        self.outcountry_cb.setText(_translate("MainWindow", "ЗА ГРАНИЦУ"))
        self.outcountry_warm_cb.setText(_translate("MainWindow", "ТЕПЛО"))
        self.outcountry_cold_cb.setText(_translate("MainWindow", "ХОЛОДНО"))
        self.outcountry_warm_hike_cb.setText(_translate("MainWindow", "ПОХОД С ПАЛАТКАМИ"))
        self.outcountry_warm_excursion_cb.setText(_translate("MainWindow", "ЭКСКУРСИЯ"))
        self.outcounty_cold_excursion_cb.setText(_translate("MainWindow", "ЭКСКРУСИЯ"))
        self.outcountry_cold_hike_cb.setText(_translate("MainWindow", "ПОХОД С ПАЛАТКАМИ"))
        self.button_travel.setText(_translate("MainWindow", "GET CHECKLIST!"))
